### ISSUE TITLE
[dev.icinga.com #2921] add full selinux support

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga-core#1052]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/2921

**Created by mfriedrich on 2012-07-30 21:15:42 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-06-12 17:06:18 +00:00 (in Redmine)_

---

this is still missing in the packages, and is currently the final showstopper for EPEL upstream.

there might be insights on the work Chris already made (check selinux/), plus maybe some insights from this howto as well
http://mbrownnyc.wordpress.com/technology-solutions/reliability-monitoring-solution/implement-icinga-on-centos6-with-selinux/

**Attachments**

* [icinga.fc](https://dev.icinga.com/attachments/download/997/icinga.fc) dgoetz - _2012-08-13 12:19:08 +00:00_ - _Filecontexts_
* [icinga.if](https://dev.icinga.com/attachments/download/998/icinga.if) dgoetz - _2012-08-13 12:19:08 +00:00_ - _Interfaces_
* [icinga.te](https://dev.icinga.com/attachments/download/999/icinga.te) dgoetz - _2012-08-13 12:19:08 +00:00_ - _Typeenforcement_
* [icinga.sh](https://dev.icinga.com/attachments/download/1000/icinga.sh) dgoetz - _2012-08-13 12:19:08 +00:00_ - _Compile and Deploy script_

**Changesets**

_2012-08-31 13:29:40 +00:00_ by _mfriedrich_ 06043e2244acb189649a4d796090c480e0fb5148

    selinux: import policy files for fc17 from #2921
    
    refs #2921

---

**Relations**:

* relates [#1666](https://dev.icinga.com/issues/1666)

**Comment by dnsmichi** [comment]
Won't happen, we have that in 2.x.
