### ISSUE TITLE
[dev.icinga.com #7277] reload while check executing causes immediate DOWN;HARD, skipping remaining attempts

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga-core#1519]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7277

**Created by mckslim on 2014-09-18 20:03:13 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-08-04 18:59:49 +00:00 (in Redmine)_

    Icinga Version: 1.11.4
    OS Version: Red Hat Enterprise Linux Server release 5.10 (Tikanga)

---

Here is an example:
\[2014-09-16 07:56:11\] HOST ALERT: P00000008057091;DOWN;SOFT;14;CRITICAL: Connection timed out to '50.73.129.57' after 160 seconds (user 'ibm\_hlth\_chk'). Expected prompt not found. Last output was ''. Attempt 14 of 19. . Traceroute completed, increased max\_attempts to 19.
(another check starts in here)
\[2014-09-16 08:01:59\] Caught SIGHUP, restarting...
(check completes in here)
\[2014-09-16 08:05:17\] Event loop started...
\[2014-09-16 08:05:18\] HOST ALERT: P00000008057091;DOWN;HARD;19;CRITICAL: Connection timed out to '50.73.129.57' after 160 seconds (user 'ibm\_hlth\_chk'). Expected prompt not found. Last output was ''. Attempt 15 of 19. . Traceroute completed, increased max\_attempts to 19.
\[2014-09-16 08:05:18\] HOST NOTIFICATION: soc;P00000008057091;DOWN;cpe\_outage\_ticket;CRITICAL: Connection timed out to 50.73.129.57 after 160 seconds (user ibm\_hlth\_chk). Expected prompt not found. Last output was . Attempt 15 of 19. . Traceroute completed, increased max\_attempts to 19.

See that the check before reload (SIGHUP) was attempt 14 of 19.
And see that check result after reload was DOWN;HARD;19, thus it went HARD on attempt 15 before getting to attempt 19.
Why is this happening? This causes premature NOTIFS to occur, which increases the amount of problems we have to process.

---

**Relations**:

* relates [#4494](https://dev.icinga.com/issues/4494)
* relates [#3899](https://dev.icinga.com/issues/3899)
* relates [#6480](https://dev.icinga.com/issues/6480)

**Comment by dnsmichi** [comment]
You might want to try this patch: https://github.com/NagiosEnterprises/nagioscore/commit/d3187897cd4d4ab1702074892b27855cf65bd992

**Comment by dnsmichi** [comment]
This was fixed in d2cf76522b already.
