### ISSUE TITLE
[dev.icinga.com #12956] Notification type differences in classic UI output.

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga-core#1585]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12956

**Created by vaisov on 2016-10-21 15:03:14 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-07 22:37:21 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    OS Version: any

---

We had server running out of space and somehow we saw exit status 2 in NRPE log, however in Icinga notification history I see type "UNKNOWN". But in other view I don't see it. Screenshots attached for better understanding of the issue.

NRPE Output:
![Clip2net_161021180042.png](https://dev.icinga.com/attachments/download/3721/Clip2net_161021180042.png)

Alert history:
![Clip2net_161021180025.png](https://dev.icinga.com/attachments/download/3722/Clip2net_161021180025.png)

Notification History
![Clip2net_161021180007.png](https://dev.icinga.com/attachments/download/3723/Clip2net_161021180007.png)

**Attachments**

* [Clip2net_161021180042.png](https://dev.icinga.com/attachments/download/3721/Clip2net_161021180042.png) vaisov - _2016-10-21 15:01:02 +00:00_ - _NRPE Output_
* [Clip2net_161021180025.png](https://dev.icinga.com/attachments/download/3722/Clip2net_161021180025.png) vaisov - _2016-10-21 15:01:03 +00:00_ - _Alert history_
* [Clip2net_161021180007.png](https://dev.icinga.com/attachments/download/3723/Clip2net_161021180007.png) vaisov - _2016-10-21 15:01:09 +00:00_ - _Notification History_

**Comment by dnsmichi** [comment]
@bb-Ricardo  Do you have a PR or can I just close it?

**Comment by dnsmichi** [comment]
Forget it. This is a wontfix too. Only security updates and minor patches around, 1.14.1 will be last release for 1.x.
