### ISSUE TITLE
[dev.icinga.com #2613] enhance solaris packaging

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga-core#973]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/2613

**Created by Tommi on 2012-05-16 06:08:05 +00:00**

Assignee: _crfriend_
Status: _Assigned_ 
Target Version: _Backlog_
Last Update: _2015-05-18 12:17:33 +00:00 (in Redmine)_

---

packaging for solaris needs to be enhanced in several points, esp full support for all configure options and solaris specific configs like zones, creating a package for idoutils, maybe additional an adopted package for nagios plugins and finaly upstream to a common distributor (i suggest www.opencsw.org)

**Changesets**

_2013-07-21 18:36:25 +00:00_ by _crfriend_ 5ac67c3a10b667fbb0dc49b1a940f73cc60d73d9

    Issue #2613 -- Enhance Solaris Packaging
    
       This commit represents changes made to the Solaris packaging
    routine to ensure proper install/removal of packages and files
    from /etc/icinga (configuration), /var/icinga (state and logs),
    and /usr/local/icinga (executables, HTML, and libraries).
    
       The change to Makefile.in is to ensure that the installation
    script can be found as the Solaris package is generated; a Solaris
    "preinstall" file is now used to make sure that the "icinga" user
    and group is present, and the postinstall now makes sure that
    permissions, UIDs and GIDs are icinga:icinga for configuration
    and state data.
    
    refs #2613

_2013-08-24 17:04:31 +00:00_ by _crfriend_ c20159937534b091cd12a76343234808d08a8cb2

    Enhance Solaris Packaging -- #2613
    
    The commit furthers the work on #2613 by clarifying the behaviour of
    the shell-script installer on systems where a GNU-style install facility
    (e.g. "ginstall") exists.  Previously the Makefile.in was not good at
    properly locating the installer during the "gmake Prototype" phase of
    the package build; this fixes it for any detected installer.
    
    refs #2613

_2013-08-25 12:59:39 +00:00_ by _crfriend_ d83f3f88395a85b66e75df887dc8517c33a453bb

    Update Makefile.in to properly deal with GNU installers -- 2613
    
    This update creates a new-style branch in "feature" for the Solaris
    Package Enhancment task and checks in the new Makefile.in which
    solves problems with either the presence or absence of GNU-style
    installers.  All installers, including the locally-supplied script
    now work.
    
    refs #2613

_2013-08-25 13:02:24 +00:00_ by _crfriend_ 58f713bd9d9ccddeff49d05336d186e52cf5a91d

    Enhance Solaris Packaging - 2613
    
    This puts some intelligence into the preremove script to not
    delete the "icinga" entries in /etc/passwd and /etc/group in
    case the removal preceds an immediate reinstallation to upgrade
    Icinga.  The flag is a valid /etc/icinga/icinga.cfg file.
    
    refs #2613

_2013-08-25 16:02:19 +00:00_ by _crfriend_ 08e8ac9f83e4d8586c4c9d58b7e024ca37d906b1

    Enhance Solaris Packaging -- #2613
    
    This is the beginning of splitting out the IDO facility from the
    base Icinga component to facilitate packaging for Solaris.  This
    will allow folks who cannot get over the "dependency hump" to
    install an IDO-free instance and at least get the benefit of the
    classic CGIs and monitoring.
    
    The new Makefile.in is smart enough to suppress the installation
    of the IDO bits into Solaris package if IDO is not in use and to
    provide it if it is.
    
    I'm committing at the moment so I don't forget and check something
    else out and blow away my changes.
    
    refs #2613

_2013-08-25 18:24:59 +00:00_ by _crfriend_ 4ea13c77f0ae79e7192ea4dc42bdb3057b6ba6cf

    Enhance Solaris Packaging -- 2613
    
    This one fixes some stupidity and fat-finger bits.  I get
    those from time to time.
    
    refs #2613

---

**Relations**:

* relates [#2609](https://dev.icinga.com/issues/2609)
* relates [#2613](https://dev.icinga.com/issues/2613)
* relates [#9020](https://dev.icinga.com/issues/9020)

**Comment by dnsmichi** [comment]
This won't happen anymore.
